services:
  kafka:
    image: bitnami/kafka:3.7 # Using a specific stable version is good practice
    container_name: kafka
    ports:
      - "9092:9092"   # Port for external access from your host machine
      - "29092:29092" # Port for internal access within the Docker network
      - "9093:9093"   # KRaft controller port
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093

      # Listener configuration
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    volumes:
      - ./kafka-data:/bitnami/kafka

  
    
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      # Connect Kafdrop to the internal listener of Kafka
      - KAFKA_BROKER_CONNECT=kafka:29092
    depends_on:
      - kafka


# example 1: local (single broker)
#environment:
  #KAFKA_NODE_ID: 1  #

# example 2: production (3 Brokers)
# Broker 1
#environment:
  #KAFKA_BROKER_ID: 1

# Broker 2
#environment:
  #KAFKA_BROKER_ID: 2

# Broker 3
#environment:
  #KAFKA_BROKER_ID: 3