services:
  kafka:
    image: bitnami/kafka:3.7
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_NUM_PARTITIONS=3
    volumes:
      - kafka-data:/bitnami/kafka

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKER_CONNECT=kafka:29092
    depends_on:
      - kafka

  topic-init:
    image: bitnami/kafka:3.7
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-c"]
    command: >
      kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists
      --topic likes --partitions 3 --replication-factor 1
    restart: "no"

  producer-api:
    build: .
    command: ["python", "producer.py"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=likes
    ports:
      - "5001:5001"
    depends_on:
      - kafka
      - topic-init

  consumer-1:
    build: .
    command: ["python", "consumer.py"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=likes
      - KAFKA_GROUP_ID=likes-ui
    depends_on:
      - kafka
      - topic-init

  consumer-2:
    build: .
    command: ["python", "consumer.py"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=likes
      - KAFKA_GROUP_ID=likes-ui
    depends_on:
      - kafka
      - topic-init

  consumer-3:
    build: .
    command: ["python", "consumer.py"]
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=likes
      - KAFKA_GROUP_ID=likes-ui
    depends_on:
      - kafka
      - topic-init

  producer-ui:
    build: .
    command:
      [
        "streamlit",
        "run",
        "producer_ui.py",
        "--server.address=0.0.0.0",
        "--server.port=8501",
      ]
    environment:
      - PRODUCER_API_URL=http://producer-api:5001
    ports:
      - "8501:8501"
    depends_on:
      - producer-api

volumes:
  kafka-data:
